name: Lint

on: [push, pull_request]

concurrency:
  group: "${{ github.ref }}#${{ github.workflow}}"
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.10'

jobs:
  python-black-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        lfs: true

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: pip install black

    - name: Lint python files
      run: black --check .
